name: Flutter Desktop CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest    env:
      FLUTTER_BUILD_DIR: build/windows/x64/runner/Release
      INSTALLER_OUTPUT_DIR: build/windows
      INSTALLER_FILENAME: ComputerInteractInstaller.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./computer_interact_thing

      - name: Analyze project
        run: flutter analyze
        working-directory: ./computer_interact_thing

      - name: Run tests
        run: flutter test
        working-directory: ./computer_interact_thing

      - name: Build Windows app
        run: flutter build windows --release
        working-directory: ./computer_interact_thing

      - name: Install NSIS
        run: choco install nsis -y

      - name: Debug Paths
        run: |
          echo "FLUTTER_BUILD_DIR=$env:FLUTTER_BUILD_DIR"
          echo "INSTALLER_OUTPUT_DIR=$env:INSTALLER_OUTPUT_DIR"
          echo "INSTALLER_FILENAME=$env:INSTALLER_FILENAME"
        working-directory: ./computer_interact_thing

      - name: Verify Installer File
        run: |
          if (!(Test-Path "../windows/installer/installer.nsi")) {
            Write-Error "Error: ../windows/installer/installer.nsi not found!"
            exit 1
          } else {
            Write-Host "installer.nsi found successfully."
          }
        working-directory: ./computer_interact_thing

      - name: Debug Build Output
        run: |
          echo "Listing contents of $env:FLUTTER_BUILD_DIR (expected: computer_interact_thing\\build\\windows\\x64\\runner\\Release)"
          dir "$env:FLUTTER_BUILD_DIR"
          echo "Expected executable: $env:FLUTTER_BUILD_DIR\\computer_interact_thing.exe"
          if (Test-Path "$env:FLUTTER_BUILD_DIR\\computer_interact_thing.exe") {
            echo "Executable FOUND at $env:FLUTTER_BUILD_DIR\\computer_interact_thing.exe"
          } else {
            echo "Executable NOT FOUND at $env:FLUTTER_BUILD_DIR\\computer_interact_thing.exe"
            echo "Searching for computer_interact_thing.exe in entire build/windows directory..."
            dir build\\windows -Recurse -Filter computer_interact_thing.exe -ErrorAction SilentlyContinue
            if (!($?)) { # Check if the previous command found anything
                echo "computer_interact_thing.exe not found anywhere in build/windows"
            }
          }
        working-directory: ./computer_interact_thing

      - name: Create Windows installer
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" ../windows/installer/installer.nsi
        working-directory: ./computer_interact_thing

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsInstaller
          path: ./computer_interact_thing/build/windows/ComputerInteractInstaller.exe
